services:
  - type: web
    name: moodtunes-pwa
    env: python
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --workers 2 --timeout 120
    # Note: app:app refers to app.py file and the Flask app instance within it
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"