services:
  - type: web
    name: moodtunes-pwa
    env: python
    buildCommand: ./build.sh
    startCommand: ./start.sh
    # Note: start.sh verifies app.py and starts gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHONUNBUFFERED
        value: "1"